"""basic kanban board database

Revision ID: 423dd6592876
Revises: eb6307302f36
Create Date: 2025-02-28 01:21:23.953909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423dd6592876'
down_revision: Union[str, None] = 'eb6307302f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('role', sa.Enum('FRONTEND', 'BACKEND', 'FULLSTACK', 'DEVOPS', 'QA', 'DESIGNER', name='userrole'), nullable=False))
    op.alter_column('users', 'minio_resume_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'minio_resume_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_table('tasks')
    # ### end Alembic commands ###
